# Generated by Django 5.0.1 on 2024-01-29 19:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdblogapp', '0007_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, null=True, populate_from='name', unique=True),
        ),
    ]
