# Generated by Django 5.0.1 on 2024-02-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdblogapp', '0012_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_prime_user',
            field=models.BooleanField(default=False),
        ),
    ]
