# Generated by Django 5.0.1 on 2024-03-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdblogapp', '0017_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
