# Generated by Django 5.0.1 on 2024-03-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdblogapp', '0018_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
