# Generated by Django 5.0.1 on 2024-03-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdmember', '0005_rename_otps_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email_expiry_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_expiry_time',
            field=models.DateTimeField(),
        ),
    ]
